import re
import csv

from scrapy.selector import HtmlXPathSelector
from scrapy.contrib.linkextractors.sgml import SgmlLinkExtractor
from scrapy.contrib.spiders import CrawlSpider, Rule
#from rubytoolbox.items import RubytoolboxItem

class RubytoolboxSpider(CrawlSpider):
    domain_name = 'ruby-toolbox.com'
    start_urls = [
        "http://ruby-toolbox.com/categories/activerecord_default_values.html",
        "http://ruby-toolbox.com/categories/activerecord_encryption.html",
        "http://ruby-toolbox.com/categories/activerecord_enumerations.html",
        "http://ruby-toolbox.com/categories/activerecord_index_assist.html",
        "http://ruby-toolbox.com/categories/activerecord_named_scopes.html",
        "http://ruby-toolbox.com/categories/activerecord_nesting.html",
        "http://ruby-toolbox.com/categories/activerecord_sharding.html",
        "http://ruby-toolbox.com/categories/activerecord_soft_delete.html",
        "http://ruby-toolbox.com/categories/activerecord_sortables.html",
        "http://ruby-toolbox.com/categories/activerecord_user_stamping.html",
        "http://ruby-toolbox.com/categories/activerecord_value_cleanup.html",
        "http://ruby-toolbox.com/categories/activerecord_versioning.html",
        "http://ruby-toolbox.com/categories/api_clients.html",
        "http://ruby-toolbox.com/categories/asynchronous_http.html",
        "http://ruby-toolbox.com/categories/backups.html",
        "http://ruby-toolbox.com/categories/browser_testing.html",
        "http://ruby-toolbox.com/categories/calendars.html",
        "http://ruby-toolbox.com/categories/code_metrics.html",
        "http://ruby-toolbox.com/categories/content_management_systems.html",
        "http://ruby-toolbox.com/categories/continuous_integration.html",
        "http://ruby-toolbox.com/categories/continuous_testing.html",
        "http://ruby-toolbox.com/categories/couchdb_clients.html",
        "http://ruby-toolbox.com/categories/crm_apps.html",
        "http://ruby-toolbox.com/categories/css_frameworks.html",
        "http://ruby-toolbox.com/categories/css_with_ruby.html",
        "http://ruby-toolbox.com/categories/daemonizing.html",
        "http://ruby-toolbox.com/categories/daemon_management.html",
        "http://ruby-toolbox.com/categories/dependency_management.html",
        "http://ruby-toolbox.com/categories/deployment_automation.html",
        "http://ruby-toolbox.com/categories/distributed_testing.html",
        "http://ruby-toolbox.com/categories/documentation_tools.html",
        "http://ruby-toolbox.com/categories/e_commerce.html",
        "http://ruby-toolbox.com/categories/e_mail_processing.html",
        "http://ruby-toolbox.com/categories/e_mail.html",
        "http://ruby-toolbox.com/categories/exception_notification.html",
        "http://ruby-toolbox.com/categories/forum_systems.html",
        "http://ruby-toolbox.com/categories/game_libraries.html",
        "http://ruby-toolbox.com/categories/gem_creation.html",
        "http://ruby-toolbox.com/categories/gem_doc_viewers.html",
        "http://ruby-toolbox.com/categories/geocoding___maps.html",
        "http://ruby-toolbox.com/categories/graphing.html",
        "http://ruby-toolbox.com/categories/html_parsing.html",
        "http://ruby-toolbox.com/categories/http_clients.html",
        "http://ruby-toolbox.com/categories/i18n.html",
        "http://ruby-toolbox.com/categories/image_processing.html",
        "http://ruby-toolbox.com/categories/irb_tools.html",
        "http://ruby-toolbox.com/categories/irc_bots.html",
        "http://ruby-toolbox.com/categories/javascript_frameworks.html",
        "http://ruby-toolbox.com/categories/javascript_testing.html",
        "http://ruby-toolbox.com/categories/javascript_tools.html",
        "http://ruby-toolbox.com/categories/ldap.html",
        "http://ruby-toolbox.com/categories/markup_processors.html",
        "http://ruby-toolbox.com/categories/microformats.html",
        "http://ruby-toolbox.com/categories/mocking.html",
        "http://ruby-toolbox.com/categories/mocking_web_requests.html",
        "http://ruby-toolbox.com/categories/mongodb_clients.html",
        "http://ruby-toolbox.com/categories/music___midi.html",
        "http://ruby-toolbox.com/categories/packaging_systems.html",
        "http://ruby-toolbox.com/categories/packaging_to_executables.html",
        "http://ruby-toolbox.com/categories/pdf_generation.html",
        "http://ruby-toolbox.com/categories/presentation_software.html",
        "http://ruby-toolbox.com/categories/project_management.html",
        "http://ruby-toolbox.com/categories/prototype_replacements.html",
        "http://ruby-toolbox.com/categories/queueing.html",
        "http://ruby-toolbox.com/categories/rails_admin_interfaces.html",
        "http://ruby-toolbox.com/categories/rails_app_templates.html",
        "http://ruby-toolbox.com/categories/rails_asset_management.html",
        "http://ruby-toolbox.com/categories/rails_authentication.html",
        "http://ruby-toolbox.com/categories/rails_authorization.html",
        "http://ruby-toolbox.com/categories/rails_captcha.html",
        "http://ruby-toolbox.com/categories/rails_comments.html",
        "http://ruby-toolbox.com/categories/rails_controller_abstractions.html",
        "http://ruby-toolbox.com/categories/rails_db_bootstrapping.html",
        "http://ruby-toolbox.com/categories/rails_file_uploads.html",
        "http://ruby-toolbox.com/categories/rails_fixture_replacement.html",
        "http://ruby-toolbox.com/categories/rails_form_builders.html",
        "http://ruby-toolbox.com/categories/rails_in_place_editing.html",
        "http://ruby-toolbox.com/categories/rails_instrumentation.html",
        "http://ruby-toolbox.com/categories/rails_menu_builders.html",
        "http://ruby-toolbox.com/categories/rails_pagination.html",
        "http://ruby-toolbox.com/categories/rails_permalinks___slugs.html",
        "http://ruby-toolbox.com/categories/rails_presenters.html",
        "http://ruby-toolbox.com/categories/rails_ratings.html",
        "http://ruby-toolbox.com/categories/rails_search.html",
        "http://ruby-toolbox.com/categories/rails_subdomains.html",
        "http://ruby-toolbox.com/categories/rails_tagging.html",
        "http://ruby-toolbox.com/categories/rails_wizards.html",
        "http://ruby-toolbox.com/categories/random_data_generation.html",
        "http://ruby-toolbox.com/categories/recurring_events.html",
        "http://ruby-toolbox.com/categories/reporting.html",
        "http://ruby-toolbox.com/categories/rss_feed_parsing.html",
        "http://ruby-toolbox.com/categories/ruby_version_management.html",
        "http://ruby-toolbox.com/categories/scheduling.html",
        "http://ruby-toolbox.com/categories/scripting_frameworks.html",
        "http://ruby-toolbox.com/categories/security_tools.html",
        "http://ruby-toolbox.com/categories/server_monitoring.html",
        "http://ruby-toolbox.com/categories/soap.html",
        "http://ruby-toolbox.com/categories/social_networking.html",
        "http://ruby-toolbox.com/categories/spam_detection.html",
        "http://ruby-toolbox.com/categories/state_machines.html",
        "http://ruby-toolbox.com/categories/static_website_generation.html",
        "http://ruby-toolbox.com/categories/syntax_highlighting.html",
        "http://ruby-toolbox.com/categories/systems_integration.html",
        "http://ruby-toolbox.com/categories/template_languages.html",
        "http://ruby-toolbox.com/categories/testing_frameworks.html",
        "http://ruby-toolbox.com/categories/text_editors_in_ruby.html",
        "http://ruby-toolbox.com/categories/time_warping.html",
        "http://ruby-toolbox.com/categories/visualizing_data.html",
        "http://ruby-toolbox.com/categories/web_app_frameworks.html",
        "http://ruby-toolbox.com/categories/web_servers.html",
        "http://ruby-toolbox.com/categories/wiki_apps.html",
        "http://ruby-toolbox.com/categories/xml_mapping.html",
    ]

    def parse(self, response):
        c = csv.writer(open('./github_data.csv', 'a'))
        xs = HtmlXPathSelector(response)
        category = xs.select('///h1/text()').extract()
        print category
        for url in xs.select('//a[@class="github_repo"]/@href').extract():
            print url
            c.writerow([category, url])
                

SPIDER = RubytoolboxSpider()
